version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:latest
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: install
          command: npm i
      - run:
          name: build
          command: npm run build
  publish:
    executor: node
    steps:
      - checkout
      - run:
          name: install
          command: npm i
      - run:
          name: build
          command: npm run build
      - run:
          name: show environment
          command: echo $SENDGRID_API_KEY
      - run:
          name: set environment
          command: echo 'export SENDGRID_API_KEY="${SENDGRID_API_KEY}"' >> $BASH_ENV
      - run:
          name: show environment
          command: echo $SENDGRID_API_KEY
      - run:
          name: upload
          command: npm run upload
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - publish:
          context: sendgrid-publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
